### ISSUE TITLE
Reproduce the imitation result.

### ISSUE THREAD

**Issue by Jarvis-K** [usail-hkust/LLMTSCS#12]
1. In what format should I prepare the collecting data? Can u provide the imitation data collection script?
2. Can u provide the imitation data in one road to help a quick reproduction?

**Comment by Gungnir2099** [comment]
You can run `run_chatgpt.py` to collect the fine-tuning data. It will be stored in `./GPT_logs`.

**Comment by Gungnir2099** [comment]
The file is named `XXX_state_action_prompt_commonsense_no_calculation.json`.

**Comment by DA21S321D** [comment]
Since the simulation time is 3600 for anon_4_4_hangzhou_real.json, how many rounds are needed to collect data from gpt4?

**Comment by Gungnir2099** [comment]
The duration of the green signal phase is 30s. So, the collection needs about 120 rounds.

**Comment by Gungnir2099** [comment]
In response to your concern, we provide the budget (in USD) for training LightGPT (with A800 GPUs) on the Jinan 1 dataset.

|      | Data Collection | Imitation Fine-tuning (1 GPU) | Critic-Guided Policy Refinement (4 GPUs) |   Sum   |
| :--: | :-------------: | :---------------------------: | :--------------------------------------: | :-----: |
| Cost |     $135.53     |            $58.00             |                  $5.52                   | $199.05 |

**Comment by DA21S321D** [comment]
Could you share just one map data collected with gpt? So that we don't have to run it again for the same thing. Thanks

**Comment by Jarvis-K** [comment]
> You can run `run_chatgpt.py` to collect the fine-tuning data. It will be stored in `./GPT_logs`.

The format of GPT_logs/xxx.json is not compatible with imitation learning. How can I transform the {state, state_incoming, prompt, action} to {instruction, output} which is required for imitation finetuning.

**Comment by Gungnir2099** [comment]
> Could you share just one map data collected with gpt? So that we don't have to run it again for the same thing. Thanks

I'm sorry, but our collected fine-tuning data for LLMLight isn't publicly available at this time because we're constantly refining it. However, the LightGPT trained on the Jinan 1 dataset is accessible. You're welcome to use its responses and gather data for additional fine-tuning purposes.

**Comment by Gungnir2099** [comment]
> > You can run `run_chatgpt.py` to collect the fine-tuning data. It will be stored in `./GPT_logs`.
> 
> The format of GPT_logs/xxx.json is not compatible with imitation learning. How can I transform the {state, state_incoming, prompt, action} to {instruction, output} which is required for imitation finetuning.

I have included the code for compiling {state, state_incoming, prompt, action} into {instruction, output} format. You can run `python finetune/state_action_2_instructions.py --input_file STATE_ACTION_PROMPT_FILE --output_file INSTRUCTION_FILE` to perform the transformation. Thank you for your feedback.

**Comment by DA21S321D** [comment]
Thanks for your kindness. I also checked this script. Since there are different files for different intersections : `Hangzhou-4_4-anon_4_4_hangzhou_real-intersection_1_1-gpt-4-4_state_action_prompt_commonsense_no_calculation.json` and `Hangzhou-4_4-anon_4_4_hangzhou_real-intersection_1_2-gpt-4-4_state_action_prompt_commonsense_no_calculation.json`  ..., should i merge their output json (generated by running `finetune/state_action_2_instructions.py`) together as the instruction file to finetune this? :
```
python ./finetune/run_imitation_finetune.py --base_model MODEL_PATH 
                                            --data_path instruction file merged 
                                            --output_dir OUTPUT_DIR
```
> > > You can run `run_chatgpt.py` to collect the fine-tuning data. It will be stored in `./GPT_logs`.
> > 
> > 
> > The format of GPT_logs/xxx.json is not compatible with imitation learning. How can I transform the {state, state_incoming, prompt, action} to {instruction, output} which is required for imitation finetuning.
> 
> I have included the code for compiling {state, state_incoming, prompt, action} into {instruction, output} format. You can run `python finetune/state_action_2_instructions.py --input_file STATE_ACTION_PROMPT_FILE --output_file INSTRUCTION_FILE` to perform the transformation. Thank you for your feedback.

**Comment by Gungnir2099** [comment]
> Thanks for your kindness. I also checked this script. Since there are different files for different intersections : `Hangzhou-4_4-anon_4_4_hangzhou_real-intersection_1_1-gpt-4-4_state_action_prompt_commonsense_no_calculation.json` and `Hangzhou-4_4-anon_4_4_hangzhou_real-intersection_1_2-gpt-4-4_state_action_prompt_commonsense_no_calculation.json` ..., should i merge their output json (generated by running `finetune/state_action_2_instructions.py`) together as the instruction file to finetune this? :
> 
> ```
> python ./finetune/run_imitation_finetune.py --base_model MODEL_PATH 
>                                             --data_path instruction file merged 
>                                             --output_dir OUTPUT_DIR
> ```
> 
> > > > You can run `run_chatgpt.py` to collect the fine-tuning data. It will be stored in `./GPT_logs`.
> > > 
> > > 
> > > The format of GPT_logs/xxx.json is not compatible with imitation learning. How can I transform the {state, state_incoming, prompt, action} to {instruction, output} which is required for imitation finetuning.
> > 
> > 
> > I have included the code for compiling {state, state_incoming, prompt, action} into {instruction, output} format. You can run `python finetune/state_action_2_instructions.py --input_file STATE_ACTION_PROMPT_FILE --output_file INSTRUCTION_FILE` to perform the transformation. Thank you for your feedback.

Yes. Each file includes the interaction records at an intersection. You can merge them all to build your instruction fine-tuning dataset.

**Comment by Jarvis-K** [comment]
Thanks for your response! It does address my issues. This issue gonna be closed.
