### ISSUE TITLE
imitation_fine_tuning_data_jinan_1.json文件如何得到

### ISSUE THREAD

**Issue by gzh-2001** [usail-hkust/LLMTSCS#27]
您好，运行run_imitation_fineturn.py需要imitation_fine_tuning_data_jinan_1.json文件，但是我好像没有找到它在哪里。它是否只能是通过run_chatgpt.py得到的文件？如果使用运行run_open_LLM得到的json文件，则会键值对不上。

**Comment by SQLai2099** [comment]
对，需要用run_chatgpt.py得到，你可以尝试自己修改一下这个文件的键。最近我有空会再更新一次GitHub。谢谢！
