### ISSUE TITLE
How to deal with this error?

### ISSUE THREAD

**Issue by NearCai** [usail-hkust/LLMTSCS#7]
LLMTSCS-main/utils/generator.py", line 1, in <module>
    from .config import DIC_AGENTS
ImportError: attempted relative import with no known parent package

**Comment by Gungnir2099** [comment]
Could you please post your code for running the experiment?

**Comment by Gungnir2099** [comment]
This error may occur if you are in the wrong directory. You must run the experiment under the root directory of our project.

**Comment by NearCai** [comment]
Thank you very much for your reply. I have resolved the issue using the command line

**Comment by Gungnir2099** [comment]
Can you click a star on our project? This will help a lot. Thanks!!!
